name: 'tinydungeon'
version: 0.0.1
description: >
  Tiny Dungeon
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
